image:
- name: node:6-alpine
- name: node:8-alpine
- name: node:9-alpine

cache:
  paths:
  - node_modules/

before_script:
- yarn install

stages:
  - lint
  - test

linter:
  stage: lint
  script: yarn run lint

tester:
  stage: test
  script: yarn run test
