cache:
  paths:
  - node_modules/

before_script:
- yarn install

stages:
  - test

.test_template: &test_definition  # Hidden key
  stage: test
  script:
  - yarn run lint
  - yarn run tests

test:node8:
  <<: *test_definition
  image: node:8-alpine

test:node9:
  <<: *test_definition
  image: node:9-alpine
